spring.application.name=mercadofipp
spring.datasource.url=jdbc:postgresql://autorack.proxy.rlwy.net:39436/railway
spring.datasource.username=postgres
spring.datasource.password=BSHpNJDxQKcHaVJpWbuseQrCSHbGTaMl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update